### ISSUE TITLE
Got the full coffeelint submodule folder instead of one lib .js file

### ISSUE THREAD

**Issue by k1r8r0wn** [zmbush/coffeelint-ruby#52]
Have updated the `coffeelint` version to 2.0.6 & got this:

`Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/k1r8r0wn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/coffeelint-ruby-452387789c1c/coffeelint/lib/coffeelint.js`

What I've done wrong?

**Comment by zmbush** [comment]
Have you run `rake prepare`?

**Comment by k1r8r0wn** [comment]
@zmbush  Sure, I've cloned the repo, change submodule's version, run `rake prepare`, all tests have been passed (get compiled files), commit changes (like you & other guys), add the updated gem to my project, run bundle install there & get the cloned repo of coffeelint library instead of one compiled .js file, like it is now, using current version of your gem.

P.S. Please, take a look at my repo, to investigate what it might be...

**Comment by zmbush** [comment]
I haven't tested using a git repository as a gem dependency in a very long time. Based on how the coffeelint submodule is set up, I wouldn't be surprised if it was totally broken. That being said, you could modify the prepare script to copy the `coffeelint.js` out of the coffeelint submodule, and commit it into the repo. Then you can reference that file rather than the one in the submodule.

**Comment by k1r8r0wn** [comment]
Okay, thanks, @zmbush!  I'll use the compiled version of `coffelint.js` directly. It's a pity that this gem became kinda 'deprecated'.

**Comment by zmbush** [comment]
The gem isn't deprecated. I just don't work on it much myself, because I don't use coffeescript or coffeelint anymore. However, if you wanted to open a pull request to update the gem to use a newer version of coffeelint, I'd happily merge it and release a new version of the gem. Since I don't use coffeelint, I don't keep track of when new versions come out.
